### ISSUE TITLE
Fail to run manual_control.py

### ISSUE THREAD

**Issue by pashok3d** [duckietown/gym-duckietown#195]
**Here is what i get when trying to run manual_control.py --env-name Duckietown-udem1-v0:**

**(gym-duckietown) PS C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown> python manual_control.py --env-name Duckietown-udem1-v0**

INFO:gym-duckietown:gym-duckietown 2019.0.0
INFO:gym-duckietown:Registering gym environment id: Duckietown-4way-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-loop_empty-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-loop_obstacles-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-loop_pedestrians-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-small_loop-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-small_loop_cw-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-straight_road-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-udem1-v0
INFO:gym-duckietown:Registering gym environment id: Duckietown-zigzag_dists-v0
DEBUG:gym-duckietown:loading map file "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\maps\udem1.yaml"
DEBUG:gym-duckietown:loading mesh "duckiebot.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\duckiebot.mtl"
DEBUG:gym-duckietown:loading mesh "tree.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\tree.mtl"
DEBUG:gym-duckietown:loading mesh "duckie.obj"
DEBUG:gym-duckietown:loading texture "duckie.png"
DEBUG:gym-duckietown:loading mesh "sign_stop.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\sign_stop.mtl"
DEBUG:gym-duckietown:loading texture "sign_stop.png"
DEBUG:gym-duckietown:loading texture "wood_osb.jpg"
DEBUG:gym-duckietown:loading mesh "sign_left_T_intersect.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\sign_left_T_intersect.mtl"
DEBUG:gym-duckietown:loading texture "sign_left_T_intersect.png"
DEBUG:gym-duckietown:loading texture "wood_osb.jpg"
DEBUG:gym-duckietown:loading mesh "sign_right_T_intersect.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\sign_right_T_intersect.mtl"
DEBUG:gym-duckietown:loading texture "sign_right_T_intersect.png"
DEBUG:gym-duckietown:loading texture "wood_osb.jpg"
DEBUG:gym-duckietown:loading mesh "sign_T_intersect.obj"
DEBUG:gym-duckietown:loading materials from "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\meshes\sign_T_intersect.mtl"
DEBUG:gym-duckietown:loading texture "sign_T_intersect.png"
DEBUG:gym-duckietown:loading texture "wood_osb.jpg"
DEBUG:gym-duckietown:loading mesh "house.obj"
DEBUG:gym-duckietown:loading texture "house.png"
DEBUG:gym-duckietown:loading mesh "truck.obj"
DEBUG:gym-duckietown:loading texture "truck.png"
DEBUG:gym-duckietown:loading mesh "bus.obj"
DEBUG:gym-duckietown:loading texture "bus.png"
DEBUG:gym-duckietown:loading texture "floor_1.png"
DEBUG:gym-duckietown:loading texture "curve_left_1.png"
DEBUG:gym-duckietown:loading texture "straight_1.png"
DEBUG:gym-duckietown:loading texture "3way_left_1.png"
DEBUG:gym-duckietown:loading texture "asphalt_1.png"
DEBUG:gym-duckietown:loading texture "grass_1.png"
DEBUG:gym-duckietown:loading texture "curve_right_1.png"
INFO:gym-duckietown:Starting at [3.17855059 0.         2.50921334] 4.046564835683915
INFO:gym-duckietown:Pos: [3.17855059 0.         2.50921334] angle 4.046564835683915
INFO:gym-duckietown:using DuckietownEnv
DEBUG:gym-duckietown:[3.48293684 0.         1.25781171] corresponds to tile at (5, 2) which is not drivable: {'coords': (5, 2), 'kind': 'asphalt', 'angle': 0, 'drivable': False, 'texture': <gym_duckietown.graphics.Texture object at 0x000001EA7E642DA0>, 'color': array([1, 1, 1])}
DEBUG:gym-duckietown:Invalid pose. Collision free: True On drivable area: False
DEBUG:gym-duckietown:safety_factor: 1.3
DEBUG:gym-duckietown:pos: [3.53607702 0.         1.17606593]
DEBUG:gym-duckietown:l_pos: [3.48293684 0.         1.25781171]
DEBUG:gym-duckietown:r_pos: [3.58921719 0.         1.09432016]
DEBUG:gym-duckietown:f_pos: [3.43798209 0.         1.11229772]
INFO:gym-duckietown:Starting at [3.67651851 0.         0.99629328] 5.077202458222053
INFO:gym-duckietown:Pos: [3.67651851 0.         0.99629328] angle 5.077202458222053
INFO:gym-duckietown:Pos: [3.67651851 0.         0.99629328] angle 5.077202458222053
Traceback (most recent call last):
  File "manual_control.py", line 46, in <module>
    env.render()
  File "C:\Users\pavel\Documents\Programming\Duckietown\gym-duckietown\gym_duckietown\simulator.py", line 1672, in render
    height=WINDOW_HEIGHT
  File "C:\Users\pavel\Anaconda3\envs\gym-duckietown\lib\site-packages\pyglet\image\__init__.py", line 909, in blit
    self.get_texture().blit(x, y, z, width, height)
  File "C:\Users\pavel\Anaconda3\envs\gym-duckietown\lib\site-packages\pyglet\image\__init__.py", line 1622, in blit
    glInterleavedArrays(GL_T4F_V4F, 0, array)
  File "C:\Users\pavel\Anaconda3\envs\gym-duckietown\lib\site-packages\pyglet\gl\lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: None

**Comment by Fanshaoliu** [comment]
I meet same problem
