### ISSUE TITLE
ImportError: cannot import name 'AbsFilePath' from 'zuper_commons.fs'

### ISSUE THREAD

**Issue by britig** [duckietown/gym-duckietown#245]
I am trying to run manual_control.py after installing duckie town and its dependencies. However, I am receiving the following error,

python manual_control.py 
Traceback (most recent call last):
  File "manual_control.py", line 17, in <module>
    from gym_duckietown.envs import DuckietownEnv
  File "/home/briti/gym-duckietown/src/gym_duckietown/__init__.py", line 4, in <module>
    from zuper_commons.fs import AbsFilePath
ImportError: cannot import name 'AbsFilePath' from 'zuper_commons.fs' (/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/zuper_commons/fs/__init__.py)

**Comment by britig** [comment]
I was able to solve this error by installing zuper-commons-z6 6.1.7 however I am still facing the following error:

DEBUG:commons:version: 6.1.7 *
INFO:dt-world:duckietown-world 1.0.30
INFO:zj:zj 3.0.3
INFO:dt-world:contracts 1.8.12 
Traceback (most recent call last):
  File "./manual_control.py", line 17, in <module>
    from gym_duckietown.envs import DuckietownEnv
  File "/home/briti/gym-duckietown/src/gym_duckietown/__init__.py", line 7, in <module>
    from duckietown_world.resources import list_maps2
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/__init__.py", line 26, in <module>
    from .geo import *
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/geo/__init__.py", line 2, in <module>
    from .measurements_utils import *
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/geo/measurements_utils.py", line 9, in <module>
    from duckietown_world.seqs import Sequence
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/seqs/__init__.py", line 2, in <module>
    from .constant import *
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/seqs/constant.py", line 7, in <module>
    from .tsequence import GenericSequence, X, Timestamp
  File "/home/briti/anaconda3/envs/duckietown/lib/python3.8/site-packages/duckietown_world/seqs/tsequence.py", line 63, in <module>
    assert False, sys.version_info
AssertionError: sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
