### ISSUE TITLE
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

### ISSUE THREAD

**Issue by mozturan** [duckietown/gym-duckietown#274]
installation seems alright but i got this error when i run ``manual_control.py`` and i'm not sure if its about numpy version. (i tried with different numpy versions but it doesnt work at all)

```
Traceback (most recent call last):
  File "./manual_control.py", line 35, in <module>
    env = DuckietownEnv(
  File "/home/tinrafiq/Documents/gym-duckietown/src/gym_duckietown/envs/duckietown_env.py", line 16, in __init__
    Simulator.__init__(self, **kwargs)
  File "/home/tinrafiq/Documents/gym-duckietown/src/gym_duckietown/simulator.py", line 381, in __init__
    self.reset()
  File "/home/tinrafiq/Documents/gym-duckietown/src/gym_duckietown/simulator.py", line 675, in reset
    tile_idx = self.np_random.integers(0, len(self.drivable_tiles))
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

``` 

any solutions?

**Comment by KonstantinKondratenko** [comment]
same problem :(
