### ISSUE TITLE
could not create GL context

### ISSUE THREAD

**Issue by msverma101** [duckietown/gym-duckietown#277]
python -m learning.imitation.iil-dagger. issue with this 

(gym-duckietown) student_sneha@6g-life-3090:~/Downloads/gym-duckietown$ python -m learning.imitation.iil-dagger.train
DEBUG:commons:version: 6.2.4 *
DEBUG:typing:version: 6.2.3
DEBUG:duckietown_world:duckietown-world version 6.4.3 path /home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages
DEBUG:geometry:PyGeometry-z6 version 2.1.4 path /home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages
DEBUG:aido_schemas:aido-protocols version 6.1.1 path /home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages
DEBUG:nodes:version 6.2.17 path /home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages pyparsing 3.1.1
{'audio': ('directsound', 'openal', 'pulse', 'silent'), 'debug_font': False, 'debug_gl': True, 'debug_gl_trace': False, 'debug_gl_trace_args': False, 'debug_graphics_batch': False, 'debug_lib': False, 'debug_media': False, 'debug_texture': False, 'debug_trace': False, 'debug_trace_args': False, 'debug_trace_depth': 1, 'debug_trace_flush': True, 'debug_win32': False, 'debug_x11': False, 'graphics_vbo': True, 'shadow_window': True, 'vsync': None, 'xsync': True, 'xlib_fullscreen_override_redirect': False, 'darwin_cocoa': True, 'search_local_libs': True}
DEBUG:gym-duckietown:gym-duckietown version 6.1.34 path /home/student_sneha/Downloads/gym-duckietown/src

libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/student_sneha/Downloads/gym-duckietown/learning/imitation/iil-dagger/train.py", line 2, in <module>
    from gym_duckietown.envs import DuckietownEnv
  File "/home/student_sneha/Downloads/gym-duckietown/src/gym_duckietown/envs/__init__.py", line 4, in <module>
    from gym_duckietown.envs.duckietown_env import DuckietownEnv
  File "/home/student_sneha/Downloads/gym-duckietown/src/gym_duckietown/envs/duckietown_env.py", line 5, in <module>
    from ..simulator import Simulator
  File "/home/student_sneha/Downloads/gym-duckietown/src/gym_duckietown/simulator.py", line 44, in <module>
    from .collision import (
  File "/home/student_sneha/Downloads/gym-duckietown/src/gym_duckietown/collision.py", line 6, in <module>
    from .graphics import rotate_point
  File "/home/student_sneha/Downloads/gym-duckietown/src/gym_duckietown/graphics.py", line 10, in <module>
    import pyglet.image
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/image/__init__.py", line 137, in <module>
    from pyglet.gl import *
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/student_sneha/anaconda3/envs/gym-duckietown/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
(gym-duckietown) student_sneha@6g-life-3090:~/Downloads/gym-duckietown$

**Comment by pietroluongo** [comment]
Solved this running on WSL2 by installing libstdcxx-ng on conda environment:

`conda install -c conda-forge libstdcxx-ng`
